FROM REPLACE_ME_WITH_RIGHT_CIRCLE_IMAGE
LABEL maintainer "Anirban Mukhopadhyay <anirban.mukhop@gmail.com>"

ARG rust_version

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain ${rust_version}

ENV PATH /home/circleci/.cargo/bin:$PATH
