environment-defaults: &environment-defaults
  IMAGE_NAME: anirbanmu/circleci-ruby-rust

build-defaults: &build-defaults
  docker:
    - image: circleci/buildpack-deps
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build Docker image
        command: |
          RBVER2="$(echo "$RUBY_VERSION" | cut -d. -f1-2)"
          RB2="rb$RBVER2"
          RSVER2="$(echo "$RUST_VERSION" | cut -d. -f1-2)"
          RS2="rs$RSVER2"
          RB3="rb$RUBY_VERSION"
          RS3="rs$RUST_VERSION"
          sed "s/REPLACE_ME_WITH_RIGHT_CIRCLE_IMAGE/circleci\/ruby:$RUBY_VERSION/" Dockerfile.template > Dockerfile
          docker build -t $IMAGE_NAME:$RB2-$RS2 -t $IMAGE_NAME:$RB2-$RS3 -t $IMAGE_NAME:$RB3-$RS2 -t $IMAGE_NAME:$RB3-$RS3 .
          if [ -z "$TAG_LATEST" ]; then docker tag $IMAGE_NAME:rb$RUBY_VERSION-rs$RUST_VERSION $IMAGE_NAME:latest ; else echo "not latest"; fi
    - run:
        name: Publish Docker Image to Docker Hub
        command: |
          RBVER2="$(echo "$RUBY_VERSION" | cut -d. -f1-2)"
          RB2="rb$RBVER2"
          RSVER2="$(echo "$RUST_VERSION" | cut -d. -f1-2)"
          RS2="rs$RSVER2"
          RB3="rb$RUBY_VERSION"
          RS3="rs$RUST_VERSION"
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_ACCESS_TOKEN"

          if [ -z "$TAG_LATEST" ]; then docker tag $IMAGE_NAME:rb$RUBY_VERSION-rs$RUST_VERSION $IMAGE_NAME:latest ; else echo "not tagging latest"; fi
          if [ -z "$TAG_LATEST" ]; then docker push $IMAGE_NAME:latest ; else echo "not pushing latest"; fi

          docker push $IMAGE_NAME:$RB2-$RS2
          docker push $IMAGE_NAME:$RB2-$RS3
          docker push $IMAGE_NAME:$RB3-$RS2
          docker push $IMAGE_NAME:$RB3-$RS3

version: 2
jobs:
  rb2.6.5-rs1.41.0:
    <<: *build-defaults
    environment:
      <<: *environment-defaults
      RUBY_VERSION: 2.6.5
      RUST_VERSION: 1.41.0
      TAG_LATEST: true
  rb2.6.5-rs1.40.0:
    <<: *build-defaults
    environment:
      <<: *environment-defaults
      RUBY_VERSION: 2.6.5
      RUST_VERSION: 1.40.0

workflows:
  version: 2
  build-master:
    jobs:
      - rb2.6.5-rs1.41.0:
          filters:
            branches:
              only: master
      - rb2.6.5-rs1.40.0:
          filters:
            branches:
              only: master
